type: "WrapperDataset"
config:
  root: "${paths.datasets}/s3dis/dataset=s3dis,format=orig"
  cache_root: "${paths.datasets}/s3dis/dataset=s3dis,format=npy"
  split: "train"
  areas: [1, 2, 3, 4, 6]
  pre_transform:
    - ToDict: {wrapper: "torch_geometric.data.Data"}
    - ToDict: {wrapper: "dict"}
  _wrapper:
    type: "S3disDataset"
    transform_keys: ["pre_transform"]
loader:
  shuffle: True
  batch_size: 32
  num_workers: 4
settings:
transforms:
  # transform:
  - ToDict: {wrapper: "torch_geometric.data.Data"}
  - RandomSample: {num: "${hp.num_points}", attrs: ["pos", "pos_normalized", "color", "semantic_index"]}
  - ToDict: {wrapper: "dict"}
meta:
  name: "S3DIS"
  identifier: null
  num_samples: 16733
  steps_per_epoch:
