type: "ModelNetSimple"
config:
  root: "${paths.datasets}/modelnet/dataset=modelnet${.name},format=pt"
  split: "test"
  name: "40"
  num_points: "${hp.num_points}"
  # cache_path: "${.root}/cache.pkl"
loader:
  shuffle: False
  batch_size: 32
  num_workers: 4
settings:
transforms: []
meta:
  name: "ModelNet40"
  identifier: null
  num_samples: 2468
  steps_per_epoch:
