type: "ModelNetSimple"
config:
  root: "${paths.datasets}/modelnet/by_n_pt/modelnet${.name}/${.num_points}"
  split: "train"
  name: "40"
  num_points: "${hp.num_points}"
  # cache_path: "${.root}/cache.pkl"
loader:
  shuffle: True
  batch_size: 32
  num_workers: 4
settings:
transforms: []
meta:
  name: "ModelNet40"
  identifier: null
  num_samples: 9843
  steps_per_epoch:
