defaults:
  - /paths: default
  - /env: default
  - /engine: default
  - /runner: MultitaskPointCloudCompressionRunner_single
  - /criterion: MultitaskPccRateDistortionLoss
  - /optimizer: net_aux
  - /scheduler: ReduceLROnPlateau
  - /misc: default
  - /dataset@dataset.train: modelnet40/train
  - /dataset@dataset.valid: modelnet40/valid
  - /dataset@dataset.infer: modelnet40/infer  # TODO same as valid/test?
  - _self_

paths:
  _aim_repo: "pcc"

exp:
  name: "${model.name}-${exp.description}"
  description:

model:
  name: "um-pcc-cls-only-pointnet-mmsp2023"

hp:
  num_points: 1024
  num_classes: 40

  # NOTE Use defaults for now

  # num_channels:
  #   g_a:
  #     pointwise: [3, 64, 64, 64, 128, 1024]
  #     mixer: []
  #     # mixer: [1024, 64]
  #     # mixer: [1024, 1024]
  #   task_backend: [1024, 512, 256, "${hp.num_classes}"]
  #   # task_backend: [64, 1024, 512, 256, "${hp.num_classes}"]
  # groups:
  #   g_a:
  #     pointwise: [1, 1, 1, 1, 1]

criterion:
  bpp_divide_by_num_points: False

optimizer:
  net:
    lr: 0.001
  aux:
    lr: 0.05

