type: "ModelNetSimple"
config:
  root: "${paths.datasets}/modelnet/by_num_points/modelnet${.name}/${.num_points}"
  split: "test"
  name: "10"
  num_points: "${hp.num_points}"
  # cache_path: "${.root}/cache.pkl"
loader:
  shuffle: False
  batch_size: 32
  num_workers: 4
settings:
transforms: []
meta:
  name: "ModelNet10"
  identifier: null
  num_samples: 908
  steps_per_epoch:
